### ISSUE TITLE
ModuleNotFoundError: No module named 'generate_xml'

### ISSUE THREAD

**Issue by 1vash** [markjay4k/YOLO-series#2]
Where can I find "generate xml" library? In part6 - draw_box.py need to load this module and there is nothing similar to "generate_xml"  in the repository.

**Comment by markjay4k** [comment]
it should be in the repo

**Comment by KarlMaoChina** [comment]
@markjay4k sorry but i did not find that module either

**Comment by KarlMaoChina** [comment]
@markjay4k oh my fault  I see it

**Comment by markjay4k** [comment]
no problem. It was named wrong. my fault there

**Comment by techkuji** [comment]
which name it have?

**Comment by padhariabhavesh** [comment]
rename part-7 to generate_xml.py
