### ISSUE TITLE
Generate XML code is not saving XML file

### ISSUE THREAD

**Issue by BlackCode101** [markjay4k/YOLO-series#25]
first of all thanks a lot for making really amazing tutorials and helping people to learn new things.

I am using the exact same code copied from your github to generate annotations, when i run the code the following 2 things happens:

1: it opens all the images all at once.
2: it saves .jpeg file not XML file.

when i double click the .jpeg file in the annotations folder it not showing anything.
so how can i correct this?
thanks,

**Comment by StevenS963** [comment]
I met the second problem, how do you solve this?

**Comment by StevenS963** [comment]
For the guys who come later, it works when I use png format image to train
