### ISSUE TITLE
Multiple objects annotating

### ISSUE THREAD

**Issue by masteroogway97** [markjay4k/YOLO-series#36]
Hey, @markjay4k great tutorial, man!
I'm trying to annotate more than 1 object in an image. While doing so, how to save the annotation files for those particular objects. Writing code for it was pretty confusing to me.
Is there any way that you've come across to resolve this issue?
Cheers!!

**Comment by masteroogway97** [comment]
Got the solution. Thanks, anyways!

**Comment by mpky** [comment]
@Wanderish what was your solution? I'd been using RectLabel rather than markjay's custom annotation .py.

**Comment by masteroogway97** [comment]
@mpky I got an idea from one of the comments on @markjay4k 's YouTube tutorial videos. I just made that into a function. I had to do it only for 2 objects so that method was fine. It'd be ridiculously tedious for more than that.
What's RectLabel? If you don't mind, could you share some info about it?

**Comment by mpky** [comment]
@Wanderish Mac OS app (https://rectlabel.com/) for annotation. There's like a free 14-day trial that I used.

It's really straightforward - just point it to your image filepath and annotate away.

**Comment by masteroogway97** [comment]
@mpky does it work for only Mac or other OSs, too?

**Comment by mpky** [comment]
@Wanderish it does seem to be only for Mac, but I know there are a ton of options out there for other OSes
