### ISSUE TITLE
error: [WinError 3] The system cannot find the path specified: 

### ISSUE THREAD

**Issue by fmartinet** [markjay4k/YOLO-series#5]
Hello, I am very new in coding and I got this issue while building the library:

error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'

I have no idea why it points this directory. How can I change it?

Thank you in advance for any help.

**Comment by markjay4k** [comment]
you need to install the visual c++ build tools in order for cython to work. You can download them here
http://landinghub.visualstudio.com/visual-cpp-build-tools
